# Backstage Scaffolder Template for Security Scanning via Rundeck
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: rundeck-security-scan-template
  title: Security Vulnerability Scanning
  description: Use this template to execute security scans including vulnerability assessments, dependency checks, and compliance validation.
  tags:
    - rundeck
    - security
    - scanning
    - compliance
spec:
  owner: user:guest
  type: rundeck-orchestration

  # Define parameters required for security scanning
  parameters:
    - title: Security Scanning Configuration
      required:
        - environment
        - scanType
        - targetSystem
        - severityLevel
        - reportFormat
        - notificationChannel
      properties:
        # Target environment parameter
        environment:
          title: Environment
          type: string
          description: Target environment for security scanning
          enum:
            - dev
            - staging
            - prod
            - all-environments

        # Scan type selection
        scanType:
          title: Scan Type
          type: string
          description: Type of security scan to perform
          enum:
            - vulnerability-scan
            - dependency-check
            - container-scan
            - network-scan
            - compliance-check
            - penetration-test
          default: vulnerability-scan

        # Target system
        targetSystem:
          title: Target System
          type: string
          description: System or application to scan
          enum:
            - web-application
            - api-services
            - database-servers
            - kubernetes-cluster
            - docker-images
            - infrastructure
          default: web-application

        # Severity level filter
        severityLevel:
          title: Minimum Severity Level
          type: string
          description: Minimum severity level to report
          enum:
            - critical
            - high
            - medium
            - low
            - info
          default: medium

        # Report format
        reportFormat:
          title: Report Format
          type: string
          description: Format for the security scan report
          enum:
            - json
            - xml
            - pdf
            - html
            - csv
          default: json

        # Notification channel
        notificationChannel:
          title: Notification Channel
          type: string
          description: Channel for scan completion notifications
          enum:
            - email
            - slack
            - teams
            - webhook
            - none
          default: email

        # Include false positives
        includeFalsePositives:
          title: Include False Positives
          type: boolean
          description: Include known false positives in the report
          default: false

        # Auto-remediation
        enableAutoRemediation:
          title: Enable Auto-Remediation
          type: boolean
          description: Attempt automatic remediation of low-risk findings
          default: false

        # Compliance framework
        complianceFramework:
          title: Compliance Framework
          type: string
          description: Compliance framework for validation
          enum:
            - none
            - cis-benchmarks
            - nist-800-53
            - iso-27001
            - pci-dss
            - sox
          default: none

        # Option to wait for job completion
        waitForJob:
          title: Wait for completion
          type: boolean
          description: Wait for job to complete before finishing
          default: true

  # Define the steps to execute the Rundeck job
  steps:
    - id: rundeck-execute
      name: Execute Security Scan
      action: rundeck:job:execute
      input:
        jobId: sec-scan-aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee
        projectName: SECURITY_OPS
        parameters:
          ENV: ${{ parameters.environment }}
          SCAN_TYPE: ${{ parameters.scanType }}
          TARGET_SYSTEM: ${{ parameters.targetSystem }}
          SEVERITY_LEVEL: ${{ parameters.severityLevel }}
          REPORT_FORMAT: ${{ parameters.reportFormat }}
          NOTIFICATION_CHANNEL: ${{ parameters.notificationChannel }}
          INCLUDE_FALSE_POSITIVES: ${{ parameters.includeFalsePositives }}
          ENABLE_AUTO_REMEDIATION: ${{ parameters.enableAutoRemediation }}
          COMPLIANCE_FRAMEWORK: ${{ parameters.complianceFramework }}
        waitForJob: ${{ parameters.waitForJob }}

  # Output section to provide useful links post-scan
  output:
    links:
      - title: Rundeck Execution
        url: ${{ steps['rundeck-execute'].output.executionId }}
        icon: dashboard
      - title: Security Dashboard
        url: https://security.company.com/dashboard
        icon: security
      - title: Vulnerability Management
        url: https://vuln-mgmt.company.com
        icon: shield